name: Publish a Docker image

on:
  push:
    branches:
      - release

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Container registry login
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: "Build + push image"
        run: |
          docker build . --tag ghcr.io/dontwatchmecode/yt-playlist-sync-mp3:latest
          docker push ghcr.io/dontwatchmecode/yt-playlist-sync-mp3:latest
